language: python
python: 3.5

cache:
  directories:
    - $HOME/.cache/pip


env:
  global:
    - DATABASE_URL="mysql://root:@localhost/test_bliski_publikator"
  matrix:
    - TOX_ENV=py34-dj19
    - TOX_ENV=py34-djmaster
    - TOX_ENV=py35-dj19
    - TOX_ENV=py35-djmaster

matrix:
  allow_failures:
    - env: TOX_ENV=py34-djmaster
    - env: TOX_ENV=py35-djmaster
    - env: TOX_ENV=pypy-djmaster

install:
  - pip install -U pip wheel
  - pip install tox
script:
- tox -e "$TOX_ENV"

before_install:
  - pip install codecov
after_success:
  - codecov
